services:
  - type: web
    name: users-management-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    branch: deploy/render
    region: virginia
    plan: free
    autoDeployTrigger: checksPass
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: users-management-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: users-management-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: users-management-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: users-management-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: users-management-db
          property: password
      - key: DB_SSLMODE
        value: require
      - key: APP_EMAIL_ENABLED
        value: "false"

databases:
  - name: users-management-db
    databaseName: crud_usuarios
    user: users_management
    plan: free
    region: virginia
    postgresMajorVersion: "17"
    ipAllowList: []
